name: Update the latest recipes
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-blog-posts:
    name: Update this repos' README with the latest recipes from NoNonsenseCooking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://nononsense.cooking/rss/feed.xml"
          comment_tag_name: "RECIPES"
          commit_message: "Updated README with the latest recipes"
