name: Update the latest blog posts
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-blog-posts:
    name: Update this repos' README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://riesinger.dev/feeds/feed.xml"
          comment_tag_name: "BLOG_POSTS"
